name: livebuy_flutter
description: Flutter plugin for Livebuy live-shopping SDK (iOS & Android).
version: 2.0.2
homepage: https://github.com/livebuy/livebuy-sdk/tree/main/flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: tv.livebuy.flutter
        pluginClass: LivebuyPlugin
      ios:
        pluginClass: LivebuyPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
